### ISSUE TITLE
New iOS Devices with 25 digit Udid is not supported

### ISSUE THREAD

**Issue by metalimangal** [AppiumTestDistribution/DeviceManager#59]
The new iOS Udid has 24 characters in udid, which is different from the 40 digits udid in previous iOS Phones.  

Verified in the ATD code, where we have only public final static int IOS_UDID_LENGTH = 40; as the ios udid variable mentioned for adding the iOS device, which doesn't run automation in the current iOS device.

**Comment by saikrishna321** [comment]
#48

**Comment by saikrishna321** [comment]
@chuklov @metalimangal Can you please run this test with real device running iOS 12 and iOS 13 https://github.com/AppiumTestDistribution/DeviceManager/blob/master/src/test/java/com/github/device/IOSDeviceTest.java

**Comment by saikrishna321** [comment]
@metalimangal @chuklov 

Please try with version

       <repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.AppiumTestDistribution</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version> bef9b5ac70 </version>
	</dependency>
